//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeAn()
        {
            this.TienDoes = new HashSet<TienDo>();
        }
    
        public int IDDeAn { get; set; }
        public string TenDeAn { get; set; }
        public string LoaiDeAn { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> IDNhom { get; set; }
        public Nullable<int> IDGiaoVien { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual Nhom Nhom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienDo> TienDoes { get; set; }
    }
}
