//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienDo
    {
        public int IDTienDo { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> HoanThanh { get; set; }
        public string TaiLieuBaoCao { get; set; }
        public Nullable<System.DateTime> ThoiGianBaoCao { get; set; }
        public string NhanXet { get; set; }
        public Nullable<int> IDDeAn { get; set; }
        public Nullable<int> IDSinhVien { get; set; }
        public Nullable<int> IDNhom { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual DeAn DeAn { get; set; }
        public virtual Nhom Nhom { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
